# MAIN base
baseURL = "/"
languageCode = "en-us"
title = "Digital Rights Watch"
theme = "apsho"
summaryLength = 18
#timeout = 30

[permalinks]
  blog = '/:year/:month/:day/:title/'

[taxonomies]
  author = "authors"
  category = 'category'
  tags = 'tags'
  # used to mark certain content as featured and displayed more prominently
  featured = 'featured'
# Navigation Bar
[[menu.main]]
    name = "Campaigns"
    pageRef = "/featured/campaigns"
    weight = 1
[[menu.main]]
    name = "The Latest"
    pageRef = "/blog"
    weight = 2
[[menu.main]]
    name = "Events"
    pageRef = "/featured/events"
    weight = 3
[[menu.main]]
    name = "Publications"
    pageRef = "/category/reports"
    weight = 4
[[menu.main]]
    name = "Reports"
    pageRef = "/category/reports"
    weight = 1
    parent = "Publications"
[[menu.main]]
    name = "Articles"
    pageRef = "/category/articles"
    weight = 2
    parent = "Publications"
[[menu.main]]
    name = "Submissions"
    pageRef = "/category/submissions"
    weight = 3
    parent = "Publications"
[[menu.main]]
    name = "Tools & Guides"
    pageRef = "/featured/tools-and-guides"
    weight = 4
    parent = "Publications"
[[menu.main]]
    name = "About Us"
    pageRef = "/about/vision"
    weight = 6
[[menu.main]]
  name = "Our Vision"
  pageRef = "/about/vision"
  parent = "About Us"
  weight = 1
[[menu.main]]
  name = "Our People"
  pageRef = "/about/our-people/"
  parent = "About Us"
  weight = 2

[[menu.main]]
    name = "Donate"
    url = "https://donate.digitalrightswatch.org.au"
    weight = 8
    [menu.main.params]
      callToAction = true

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "Archive"
    pageRef = "/blog"
    weight = 2
[[menu.sitemap]]
    name = "About"
    pageRef = "/about"
    weight = 2
[[menu.sitemap]]
    name = "Privacy & Policy"
    pageRef = "privacy"
    weight = 3
[[menu.sitemap]]
    name = "Contact"
    pageRef = "contact"
    weight = 4

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
        block = true
        title = true

# Footer Address
[params.address]
#address = "23 Khan Niketon, Grand Street, NYK."
email = "info@digitalrightswatch.org.au"
#phone = "+(448) 833 5272 332"

# Footer Social
[params.social]
facebook = "https://www.facebook.com/DigiRightsWatch"
instagram = "https://www.instagram.com/drwaus"
twitter = "https://twitter.com/drwaus"
github = "https://github.com/digitalrightswatch"
mastodon = "https://aus.social/@drwaus"
bsky = "https://bsky.app/profile/drwaus.bsky.social"

[params]

# Header
logo = "/wp-content/uploads/2019/07/DRWLogo_black_w_yellow.png"
logoAltText = "DRW"

# Footer
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'assets'
