# MAIN base
baseURL = "/"
languageCode = "en-us"
title = "Digital Rights Watch"
theme = "apsho"
summaryLength = 18

[permalinks]
  blog = '/:year/:month/:day/:title/'

[taxonomies]
  category = 'category'

# Navigation Bar
[[menu.main]]
    name = "Home"
    url = "/#hero"
    weight = 1
[[menu.main]]
    name = "About"
    pageRef = "about"
    weight = 2
[[menu.main]]
    name = "Donate"
    url = "https://donate.digitalrightswatch.org.au"
    weight = 3
[[menu.main]]
    name = "Blog"
    url = "/#blog"
    weight = 4

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "Latest Article"
    pageRef = "blog"
    weight = 2
[[menu.sitemap]]
    name = "Privacy & Policy"
    pageRef = "privacy"
    weight = 3
[[menu.sitemap]]
    name = "Contact"
    pageRef = "contact"
    weight = 4

[markup.goldmark.renderer]
    unsafe = true

# Footer Address
[params.address]
#address = "23 Khan Niketon, Grand Street, NYK."
email = "info@digitalrightswatch.org.au"
#phone = "+(448) 833 5272 332"

# Footer Social
[params.social]
facebook = "https://www.facebook.com/DigiRightsWatch"
instagram = "https://www.instagram.com/drwaus"
twitter = "https://twitter.com/drwaus"
github = "https://github.com/digitalrightswatch"
mastodon = "https://aus.social/@drwaus"

[params]

# Header
logo = "/wp-content/uploads/2019/07/DRWLogo_black_w_yellow.png"
fabFormURL = "https://fabform.io/f/zWMBVeW"
googleAnalytics = "UA-175025671-2"

# Footer
footerTitle = "Get the latest updates"
copyright1 = "Copyright © Digital Rights Watch {year}"
copyright2 = "Built using <a href=\"https://github.com/StaticMania/hugo-apsho\" target=\"_blank\">Apsho</a> with <a href=\"https://gohugo.io\" target=\"_blank\">Hugo</a>"

#contact
email = "help@staticmania.com"

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'assets'
