# MAIN base
baseURL = "/"
languageCode = "en-us"
title = "Digital Rights Watch"
theme = "apsho"
summaryLength = 18
#timeout = 30
# configure netlify redirects
# https://honnef.co/articles/generating-netlify-_redirects-from-hugo/
disableAliases = true

[outputFormats.REDIR]
mediaType = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

[mediaTypes."text/netlify"]
delimiter = ""

[outputs]
home = ["HTML", "RSS", "REDIR"]

[permalinks]
  blog = '/:year/:month/:day/:title/'

[taxonomies]
  author = "authors"
  category = 'category'
  tags = 'tags'
  # used to mark certain content as featured and displayed more prominently
  featured = 'featured'
# Navigation Bar
[[menu.main]]
    name = "Campaigns"
    pageRef = "/featured/campaigns"
    weight = 1
[[menu.main]]
    name = "The Latest"
    pageRef = "/blog"
    weight = 2
[[menu.main]]
    name = "Events"
    pageRef = "/featured/events"
    weight = 3
[[menu.main]]
    name = "Publications"
    pageRef = "/category/reports"
    weight = 4
[[menu.main]]
    name = "Reports"
    pageRef = "/category/reports"
    weight = 1
    parent = "Publications"
[[menu.main]]
    name = "Articles"
    pageRef = "/category/articles"
    weight = 2
    parent = "Publications"
[[menu.main]]
    name = "Submissions"
    pageRef = "/category/submissions"
    weight = 3
    parent = "Publications"
[[menu.main]]
    name = "Tools & Guides"
    pageRef = "/featured/tools-and-guides"
    weight = 4
    parent = "Publications"
[[menu.main]]
    name = "About Us"
    pageRef = "/about/"
    weight = 6
[[menu.main]]
  name = "Our Vision"
  pageRef = "/about/"
  parent = "About Us"
  weight = 1
[[menu.main]]
  name = "Our People"
  pageRef = "/about/our-people/"
  parent = "About Us"
  weight = 2
[[menu.main]]
  name = "Annual Reports"
  pageRef = "/category/annual-reports"
  parent = "About Us"
  weight = 3
[[menu.main]]
  name = "Our History"
  pageRef = "/about/our-history"
  parent = "About Us"
  weight = 4
[[menu.main]]
  name = "Contact Us"
  pageRef = "/contact"
  parent = "About Us"
  weight = 5
[[menu.main]]
    name = "Donate"
    url = "https://donate.digitalrightswatch.org.au"
    weight = 8
    [menu.main.params]
      callToAction = true
      external = true

# Footer Menu
[[menu.footer]]
    name = "About"
    pageRef = "/about/"
    weight = 1

[[menu.footer]]
    name = "Contact"
    pageRef = "/contact/"
    weight = 2

[[menu.footer]]
    name = "Privacy & Policy"
    pageRef = "privacy-policy"
    weight = 3
[[menu.footer]]
    name = "Donate"
    url = "https://donate.digitalrightswatch.org.au"
    weight = 4

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
        block = true
        title = true

# Footer Address
[params.address]
#address = "23 Khan Niketon, Grand Street, NYK."
email = "info@digitalrightswatch.org.au"
#phone = "+(448) 833 5272 332"

# Footer Social
[params.social]
facebook = "https://www.facebook.com/DigiRightsWatch"
instagram = "https://www.instagram.com/drwaus"
twitter = "https://twitter.com/drwaus"
github = "https://github.com/digitalrightswatch"
mastodon = "https://aus.social/@drwaus"
bsky = "https://bsky.app/profile/drwaus.bsky.social"

[params]

# Header
logo = "images/drw-logo-with-text.svg"
logoAltText = ""

# Footer
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'assets'
