# MAIN base
baseURL = "/"
languageCode = "en-us"
title = "Digital Rights Watch"
theme = "apsho"
summaryLength = 18
#timeout = 30

[permalinks]
  blog = '/:year/:month/:day/:title/'

[taxonomies]
  author = "authors"
  category = 'category'
  tags = 'tags'

# Navigation Bar
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    pageRef = "/about"
    weight = 2
[[menu.main]]
  name = "Our Vision"
  url = "/about/vision/"
  parent = "About"
  weight = 1
[[menu.main]]
  name = "Our People"
  url = "/about/our-people/"
  parent = "About"
  weight = 2

[[menu.main]]
    name = "The Latest"
    url = "/articles"
    weight = 3
[[menu.main]]
    name = "Newsletter"
    url = "/signup"
    weight = 4
[[menu.main]]
    name = "Donate"
    url = "https://donate.digitalrightswatch.org.au"
    weight = 5
    [menu.main.params]
      callToAction = true

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "About"
    pageRef = "/about"
    weight = 2
[[menu.sitemap]]
    name = "Privacy & Policy"
    pageRef = "privacy"
    weight = 3
[[menu.sitemap]]
    name = "Contact"
    pageRef = "contact"
    weight = 4

[markup.goldmark.renderer]
    unsafe = true

# Footer Address
[params.address]
#address = "23 Khan Niketon, Grand Street, NYK."
email = "info@digitalrightswatch.org.au"
#phone = "+(448) 833 5272 332"

# Footer Social
[params.social]
facebook = "https://www.facebook.com/DigiRightsWatch"
instagram = "https://www.instagram.com/drwaus"
twitter = "https://twitter.com/drwaus"
github = "https://github.com/digitalrightswatch"
mastodon = "https://aus.social/@drwaus"
bsky = "https://bsky.app/profile/drwaus.bsky.social"

[params]

# Header
logo = "/wp-content/uploads/2019/07/DRWLogo_black_w_yellow.png"
logoAltText = "DRW"
fabFormURL = "https://fabform.io/f/zWMBVeW"
googleAnalytics = "UA-175025671-2"

# Footer
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'assets'
